name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: webdev21/web_ci@latest
    - name: web_ci
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
